services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/client.Dockerfile
    environment:
      API_URL:
    ports:
      - '4200:4200'
  api:
    build:
      context: .
      dockerfile: ./apps/api/api.Dockerfile
    environment:
      API_KEY: ${API_KEY} #LocationIQ key
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: rwa
      ORIGIN:
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: rwa
    shm_size: 128mb
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'rwa']
      interval: 10s
      timeout: 5s
      retries: 5
