services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/client.Dockerfile
    ports:
      - '4200:4200'
  api:
    build:
      context: .
      dockerfile: ./apps/api/api.Dockerfile
    environment:
      JWT_SECRET: gqe212ubgt3bu3t13ubt3u
      GOOGLE_KEY: AIzaSyAil5ZY9_7q_dI3989slk7QHaEO97ZzS68
      DATABASE_NAME: rwa
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rwa
    shm_size: 128mb
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'rwa']
      interval: 10s
      timeout: 5s
      retries: 5
